### ISSUE TITLE
能加入browserify配置吗

### ISSUE THREAD

**Issue by levai** [zhonglimh/Ublue-gulp-config#2]
楼主 能加入browserify配置吗

**Comment by zhonglimh** [comment]
可以，我抽时间搞一个。

**Comment by levai** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    感谢，学习到了
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                2402249797
                            
                    
                        
                            
                                    2402249797@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2019年10月28日 21:46，Ryan<notifications@github.com> 写道： 


可以，我抽时间搞一个。



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
